[develop]
script_dir=$base/lib/guardrail_pkg

[install]
install_scripts=$base/lib/guardrail_pkg

[options.entry_points]
console_scripts =
    guardrail_node = guardrail_pkg.guardrail_node:main
    secure_pub = guardrail_pkg.secure_pub:main
    secure_sub = guardrail_pkg.secure_sub:main
    otp_auth_node = guardrail_pkg.otp_auth_node:main
    robot_cli = guardrail_pkg.robot_cli:main
    local_ml_guardrail = guardrail_pkg.local_ml_guardrail:main
    clarification_node = guardrail_pkg.clarification_node:main
